apiVersion: v1
kind: Service
metadata:
  name: zahnarzt-kramer-web
  namespace: web-zahnarzt-kramer
  labels:
    app.kubernetes.io/name: zahnarzt-kramer-web
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zahnarzt-kramer-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
